### ISSUE TITLE
Update documentation to mention minimum Sonatype version

### ISSUE THREAD

**Issue by kelvien** [sonatype-nexus-community/nexus-repository-cpan#1]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I am using nexus 3.7.1-02 and I am trying to follow the "(most) Permanent Install" in nexus-repository-cpan, but I'm getting the following error on running nexus run:

2018-07-24 15:53:58,802-0400 ERROR [jetty-main-1] *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Failed to initialize context
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-core-feature; type=karaf.feature; version=0; filter:="(&(osgi.identity=nexus-core-feature)(type=karaf.feature)(version>=0.0.0))" [caused by: Unable to resolve nexus-core-feature/3.7.1.02: missing requirement [nexus-core-feature/3.7.1.02] osgi.identity; osgi.identity=nexus-repository-cpan; type=karaf.feature; version="[1.0.0,1.0.0]" [caused by: Unable to resolve nexus-repository-cpan/1.0.0: missing requirement [nexus-repository-cpan/1.0.0] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-cpan; type=osgi.bundle; version="[1.0.0,1.0.0]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-cpan/1.0.0: missing requirement [org.sonatype.nexus.plugins.nexus-repository-cpan/1.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.commons.compress.archivers.tar)(version>=1.11.0))"]]]
        at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:259)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

I tried the temporary install and got this

karaf@root()> bundle:start 261
2018-07-24 16:07:35,446-0400 ERROR [Karaf local console user karaf] *SYSTEM org.apache.karaf.shell.support.ShellUtil - Exception caught while executing command
org.apache.karaf.shell.support.MultiException: Error executing command on bundles:
        Error starting bundle 261: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-cpan [261](R 261.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-cpan [261](R 261.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.8.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-cpan [261](R 261.0)] osgi.wiring.package; (&(osgi.wiring.package=org.sonatype.nexus.blobstore.api)(version>=3.8.0))]

So, apparently it requires sonatype >3.8.0. I installed the latest sonatype as of now 3.13.0-01 and it now works.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
Update documentation to mention the minimum sonatype version: >= 3.8.0

* **Anything else?**

**Comment by jlstephens89** [comment]
@kelvien Thank you for filing this, feel free to file a PR with this change and we will review.

**Comment by kelvien** [comment]
@jlstephens89 I would love to! Can you grant me permission to push my changes?

**Comment by joedragons** [comment]
@kelvien Can you not make a PR now?  My understanding is everyone can but they need to be reviewed by someone with write perms to merge.  Maybe this project is misconfigured/different.  cc/ @DarthHater

**Comment by kelvien** [comment]
@joedragons No, I can't push my branch. Getting a 403 response
```
remote: Permission to sonatype-nexus-community/nexus-repository-cpan.git denied to kelvien.
fatal: unable to access 'https://github.com/sonatype-nexus-community/nexus-repository-cpan.git/': The requested URL returned error: 403
```

**Comment by DarthHater** [comment]
You’d want to fork the repo, push the commit to your fork, and then create
a pr. We keep the list of people who can push directly to these repos
fairly succinct, mostly sonatype and people who have contributed large
amounts of code. Let me know if that doesn’t make sense!

**Comment by kelvien** [comment]
@DarthHater Thank you for the direction. It's a new process for me. Here is the PR: https://github.com/sonatype-nexus-community/nexus-repository-cpan/pull/2
